# Generated by Django 5.1.4 on 2024-12-15 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("meetup", "Meetup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                ("is_approaching", models.BooleanField(default=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("in-person", "In-Person"),
                            ("online", "Online"),
                            ("zoom", "Zoom"),
                            ("google-meet", "Google Meet"),
                            ("webex", "Webex"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
